# Numpy 및 Matlab + Pandas % 추가적으로 마크업 정리 사이트

### [마크업 사이트](https://gist.github.com/ihoneymon/652be052a0727ad59601)

># Numpy Tutorial

In [25]:
score  = [12,24,45]

In [18]:
for a in range(0,len(score)):
    score[a] += 3

In [26]:
for i,s in enumerate(score):
    score[i] += 3

enumerate : for 반복문에서 리스트를 넣어주면 index와 list.value값을 for문으로 넣어준다

In [27]:
score

[15, 27, 48]

In [28]:
!pip install numpy

     --------------------------------------- 14.7/14.7 MB 21.1 MB/s eta 0:00:00


In [31]:
!pip install pandas

     --------------------------------------- 10.6/10.6 MB 16.4 MB/s eta 0:00:00
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)


In [32]:
import numpy as np

np.__version__

'1.23.1'

>## ndarray 클래스
>> ### ndarray
>>> <img src = https://images.velog.io/images/mingki/post/e0cdf6b1-cfd0-4a64-82d1-0c489237f1c2/array_shape.png width = 500 heigh= 350><br>
>>> shape(4,)-> turple임을 알려주기 위해서 
>>> 축이 1개면 1차원, 축이 2개면 2차원, 축이 3개면 3차원 -> 축은 0부터 ...n으로 차례차례 증가한다.
>>> * Numpy에서 제공하는 N 차원 배열 객체

   > 

In [48]:
xarr = np.array([23, 45, 56, 76])
xarr

array([23, 45, 56, 76])

In [49]:
type(xarr)

numpy.ndarray

In [50]:
xarr.shape

(4,)

In [51]:
type(xarr.shape)

tuple

In [52]:
xarr.dtype

dtype('int32')

In [53]:
xarr.size

4

In [58]:
xarr.itemsize
# 바이트 수

4

In [59]:
xarr.size * xarr.itemsize
# 할당된 메모리 크기

16

In [102]:
yarr = np.array([ [[10,12],[1,2]], 
                 [[12,14],[1,2]],
                 [[15,12],[16,12]] ])

In [76]:
yarr.shape

(3, 2, 2)

In [79]:
yarr.dtype

dtype('int32')

numpy에서 형변환

In [82]:
yarr.astype('float32')

array([[[10., 12.],
        [ 1.,  2.]],

       [[12., 14.],
        [ 1.,  2.]],

       [[15., 12.],
        [16., 12.]]], dtype=float32)

In [83]:
yarr_float = yarr.astype('float32')

In [86]:
yarr.dtype

dtype('int32')

In [84]:
yarr_float

array([[[10., 12.],
        [ 1.,  2.]],

       [[12., 14.],
        [ 1.,  2.]],

       [[15., 12.],
        [16., 12.]]], dtype=float32)

In [88]:
xarr = np.array([32.,333.,321.,12.],dtype='float32')
xarr.dtype

dtype('float32')

## 차원 변경
reshape함수

In [89]:
yarr.reshape(1,3,2,2)

array([[[[10, 12],
         [ 1,  2]],

        [[12, 14],
         [ 1,  2]],

        [[15, 12],
         [16, 12]]]])

In [96]:
yarr_4d = yarr.reshape(-1,3,2,2,)
# -1을 하게되는 경우 reshape에게 차원 수정을 맡긴다는 의미)

In [94]:
yarr_4d.shape

(1, 3, 2, 2)

In [95]:
yarr_4d

array([[[[10, 12],
         [ 1,  2]],

        [[12, 14],
         [ 1,  2]],

        [[15, 12],
         [16, 12]]]])

In [101]:
yarr=yarr.reshape(3,4)

AttributeError: 'tuple' object has no attribute 'reshape'

In [103]:
yarr.reshape(-1,2,2)

array([[[10, 12],
        [ 1,  2]],

       [[12, 14],
        [ 1,  2]],

       [[15, 12],
        [16, 12]]])

In [104]:
#축추가하기

In [111]:
yarr.shape

(3, 2, 2)

In [112]:
yarr[np.newaxis,:].shape

(1, 3, 2, 2)

In [113]:
yarr[:,:,:,np.newaxis].shape

(3, 2, 2, 1)

arange()

In [115]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [120]:
np.arange(10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [121]:
np.linspace(0,10,8)
# np.linspace(A,B,C)
# A~B사이를 C개로 나누어준다

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [123]:
np.full((2,3,3),-1)

array([[[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]]])

In [125]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
yarr.shape

(3, 2, 2)

In [127]:
np.zeros_like(yarr)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

## Random

In [128]:
np.random.uniform(0,10,10)

array([3.05530942, 2.0109791 , 1.06081523, 5.43454207, 1.97524089,
       2.92109615, 3.13719646, 0.84831754, 1.42290852, 3.12137825])

In [129]:
np.random.normal(0,1, 10)

array([-0.93892324, -0.28348121,  0.66369606, -0.88224565, -0.33948066,
       -0.76113109,  0.31112529, -1.31406656,  0.12700768, -0.66972011])

In [130]:
np.random.randn(10)
#표준정규분포 0~1에서 뽑는메서드

array([-0.04649418, -0.50198438,  1.93752923, -0.77621559, -0.87828557,
        1.23687855,  0.30856228,  1.32044009,  1.19055107, -1.05663104])

In [131]:
xarr = np.arange(0,12).reshape(3,4)

In [132]:
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
xarr.sum(axis=0)

array([12, 15, 18, 21])

In [139]:
xarr[0]

array([0, 1, 2, 3])

In [141]:
xarr[:][0]

array([0, 1, 2, 3])

In [142]:
xarr.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [143]:
xarr+3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [144]:
[1,2,3]+[4]

[1, 2, 3, 4]

In [146]:
x = np.random.rand(3,4)

In [147]:
y= np.random.rand(4)

In [148]:
x

array([[0.05255582, 0.36759376, 0.13460952, 0.03820565],
       [0.34229323, 0.54553811, 0.66170286, 0.91295714],
       [0.21838849, 0.77822073, 0.08039522, 0.63958327]])

In [153]:
x[0][0]* y[0]

0.03560665274936335

In [158]:
x

array([[0.05255582, 0.36759376, 0.13460952, 0.03820565],
       [0.34229323, 0.54553811, 0.66170286, 0.91295714],
       [0.21838849, 0.77822073, 0.08039522, 0.63958327]])

In [157]:
np.dot(x,y)

array([0.44995677, 1.89629241, 1.45610212])

In [161]:
x= np.arange(0,3)
y= np.arange(1,4)

In [163]:
x

array([0, 1, 2])

In [164]:
y

array([1, 2, 3])

In [162]:
np.dot(x,y)

8

In [166]:
np.matmul(x,y)

8

In [170]:
x= np.array([1,2,3,5,1,2,5,2,31,5,2,1])
x >2

array([False, False,  True,  True, False, False,  True, False,  True,
        True, False, False])

In [173]:
x[x>2]

array([ 3,  5,  5, 31,  5])

In [186]:
x = [1,2,3]
y = [4,5,6]
z = [[1,2,3],[6,7,8]]

In [190]:
np.concatenate((x,y),axis=0)

array([1, 2, 3, 4, 5, 6])

vstack  -> 밑으로
hstack - > 옆으로 합쳐준다


In [191]:
x = np.arange(0,4).reshape(2,2)

In [192]:
x

array([[0, 1],
       [2, 3]])

In [193]:
x[1,0]

2

In [194]:
x[1][0]

2

Numpy의 인덱싱 방식은
arr[][] 가 아닌
arr[a,b,]이다

In [195]:
x = np.arange(0,6)

In [196]:
x

array([0, 1, 2, 3, 4, 5])

In [197]:
np.where(x>3)

(array([4, 5], dtype=int64),)

행 카운트 방법

In [198]:
x = np.array([1,2,3,4,5,6])
y = np.where(x>3,1,0)
y.sum()

3

In [202]:
x = np.random.randn(3,4)
x

array([[-1.00959711, -0.72442468,  0.05937016, -1.12221424],
       [ 0.25148216, -0.9546156 , -1.06949596, -1.62917662],
       [ 2.31161809,  0.17203263,  0.36338134,  0.47684578]])

In [201]:
np.argmax(x,axis=1)

array([0, 2, 3], dtype=int64)

In [203]:
x = np.arange(0,10)

In [204]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
x = np.genfromtxt('./datasets/iris.csv',delimiter=',',skip_header=1)

In [212]:
x.shape

(150, 5)

In [213]:
x.dtype

dtype('float64')

In [220]:
iris = x[:,:4].deepcopy()

AttributeError: 'numpy.ndarray' object has no attribute 'deepcopy'

In [219]:
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [221]:
iris[:,0].mean()

5.843333333333334

In [237]:
iris_big = iris[iris[:,0]>iris[:,0].mean()]

In [246]:
iris_big[:,0].min()

5.9

In [239]:
iris_sma = iris[iris[:,0]<=iris[:,0].mean()]

In [240]:
list_x = np.where(iris[:,0]>iris[:,0].mean(),1,0)

In [241]:
list_x.sum()

70

In [247]:
list_x.tofile('test.csv')


### numpy file 저장 방식

In [248]:
np.savez('my_iris.npz', x=iris_big,y=iris_sma) 

### numpy file 불러오기

In [249]:
my_iris = np.load('my_iris.npz')
type(my_iris)

numpy.lib.npyio.NpzFile

In [252]:
xarr = my_iris['x']

In [254]:
xarr.shape

(70, 4)

In [255]:
yarr = my_iris['y']

In [256]:
yarr.shape

(80, 4)